/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Front;

import Database.Connections;
import java.awt.print.PrinterException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class assignment_view extends javax.swing.JFrame {
private Connection con;
private ResultSet rs;
private Statement st;
private PreparedStatement pst;
Connections connect=new Connections();
    /**
     * Creates new form assignment_view
     */
    public assignment_view(String title) {
        initComponents();
 try{
          String query="SELECT file FROM assignment_submission WHERE title='"+title+"'";
          pst=connect.Conn().prepareStatement(query);
        rs=pst.executeQuery(query);
    File fle=new File(title+".txt");
    //    File fle=new File(title+".txt");
        FileOutputStream fout=new FileOutputStream(fle);
        if(rs.next())
        {
        InputStream input=rs.getBinaryStream("file");
        byte[] buffer=new byte[1024];
while(input.read(buffer)>0)
        {
            //BufferedReader buff=new BufferedReader(buffer);
//StringBuilder sb=new StringBuilder();
//sb.append(buffer);
            fout.write(buffer);
            FileReader fr=new FileReader(fle);
            BufferedReader br=new BufferedReader(fr);
            area.read(br,null);
        }
        }
        JOptionPane.showMessageDialog(null,"File Readed");
        read();
      }
      catch(Exception ex)
      {ex.printStackTrace();
      JOptionPane.showMessageDialog(null, ex.getMessage());} 
    }

//    public assignment_view(String title) {
//   readfile("adil");     
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        characters = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        words = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Project Proposal Submission");

        characters.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        characters.setText("Lines");

        jLabel6.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        jLabel6.setText("Characters:");

        words.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        words.setText("Lines");

        jLabel2.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        jLabel2.setText("Words:");

        jScrollPane1.setViewportView(area);

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(words, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(characters, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(words, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(characters)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//public void readfile(String title)
//{
//   
//}
public void read()
{
int spe=0;
    int wCount =1+area.getText().length() - area.getText().replaceAll(" ","").length();
int vows = 0,cons = 0,spa=0,lno=0;
words.setText(""+wCount);
String sq=area.getText();
char[] ch=new char[100];
for(int i = 0; i < sq.length(); i ++)
{
ch = sq.toCharArray();
if(ch[i] == 'a' || ch[i] == 'A' || ch[i] == 'e' || ch[i] == 'E' || ch[i] == 'i' || 
ch[i] == 'I' || ch[i] == 'o' || ch[i] == 'O' || ch[i] == 'u' || ch[i] == 'U')
{vows ++;}
else if(Character.isWhitespace(ch[i])){
spa++;
}
else{
cons ++;}
characters.setText(""+(vows+cons));          
}
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              try{
boolean complete=area.print();
if(complete){
JOptionPane.showMessageDialog(null,"Done Printing","Information",JOptionPane.INFORMATION_MESSAGE);
}else{
JOptionPane.showMessageDialog(null,"Printing","Printer",JOptionPane.ERROR_MESSAGE);
}
}
catch(PrinterException e){
JOptionPane.showMessageDialog(null, e.getMessage());
}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane area;
    private javax.swing.JLabel characters;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel words;
    // End of variables declaration//GEN-END:variables
}
