/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Front;

import Database.Connections;
import Student.Sgetset;
import Student.Spage;
import Student.Student;
import Student.sforget_account;
import Teacher.Account;
import Teacher.Tpage;
import Teacher.tforget_account;
import java.awt.Color;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Saad Shaikh
 */
public class Front extends javax.swing.JFrame {
    Connection con;
    Statement st;
    PreparedStatement pst;
    ResultSet rs;
    String ge;
    String na,nam;
    Connections connect=new Connections();
   // Front fr=new Front();
    /**
     * Creates new form Front
     */
    public Front() {
        initComponents();
        
     
       
  
        //lbl.setText("<a href="" target=_blank">Create An Account</a>");
     
       // Front fr=new Front();
//NewJPanel pne=new NewJPanel();
//pne.setVisible(true);
//view.setVisible(true);
    //fr.setVisible(false);
        Connections connect=new Connections();
      con=connect.Conn();
   forgot.setText("<html><a href=\"\">Forgot Your Password</a></html>");
    saccount.setText("<html><a href=\"\">Create Account For Teacher</a></html>");
    taccount.setText("<html><a href=\"\">Create Account For Student</a></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        taccount = new javax.swing.JLabel();
        forgot = new javax.swing.JLabel();
        student = new javax.swing.JRadioButton();
        saccount = new javax.swing.JLabel();
        teacher = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        name = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Project Proposal Submission");

        login.setBackground(new java.awt.Color(153, 153, 153));
        login.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)), "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 1, 24), new java.awt.Color(204, 204, 204))); // NOI18N

        taccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        taccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                taccountMouseEntered(evt);
            }
        });

        forgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgotMouseExited(evt);
            }
        });

        student.setBackground(new java.awt.Color(153, 153, 153));
        student.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        student.setText("As Student");
        student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentActionPerformed(evt);
            }
        });

        saccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saccountMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                saccountMousePressed(evt);
            }
        });

        teacher.setBackground(new java.awt.Color(153, 153, 153));
        teacher.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        teacher.setText("As Teacher");
        teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Quit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Password");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Name");

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taccount, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(forgot, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saccount, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(student)
                        .addGap(68, 68, 68)
                        .addComponent(teacher)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student)
                    .addComponent(teacher))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(forgot, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taccount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saccount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

public void setname(String name)
{
nam=name;
}
    private void taccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taccountMouseEntered
        taccount.setForeground(Color.GREEN);
    }//GEN-LAST:event_taccountMouseEntered

    private void forgotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMouseExited
        if(forgot.getForeground()==Color.BLUE)
        {forgot.setForeground(Color.RED);}
        else{forgot.setForeground(Color.BLUE);}
    }//GEN-LAST:event_forgotMouseExited

    private void forgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMouseClicked
        if(forgot.getForeground()==Color.blue)
        {forgot.setForeground(Color.red);}
        else{forgot.setForeground(Color.blue);}
        if(teacher.isSelected()==true)
        {tforget_account tac=new tforget_account();
        tac.show();dispose();}
        else{
        sforget_account sac=new sforget_account();
        sac.show();dispose();
        }
    }//GEN-LAST:event_forgotMouseClicked

    private void saccountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saccountMousePressed
        saccount.setForeground(Color.YELLOW);
    }//GEN-LAST:event_saccountMousePressed

    private void studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentActionPerformed

        teacher.setSelected(false);
        ge=student.getText();
    }//GEN-LAST:event_studentActionPerformed

    private void teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherActionPerformed

        student.setSelected(false);
        ge=teacher.getText();
    }//GEN-LAST:event_teacherActionPerformed
public void inserts(String nam,String pass)
{
try{
String query="INSERT INTO login_table(name,password) VALUES(?,?)";
pst=connect.Conn().prepareStatement(query);
       pst.setString(1,nam);
       pst.setString(2,pass);
       pst.execute();
}
catch(Exception ex)
{ex.printStackTrace();
JOptionPane.showMessageDialog(null,ex.getMessage());}
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //if(validatename(name.getText())==false)
        //{JOptionPane.showMessageDialog(null,"Format Not Correct");}
        //else{
       Sgetset set=new Sgetset();
       set.setnam(name.getText());
       inserts(name.getText(),password.getText());
        if(ge.equalsIgnoreCase("as Teacher"))
            {
                try{
                    String query="SELECT name,password FROM teacher_info WHERE name='"+name.getText()+"' AND password='"+password.getText()+"'";
                    pst=con.prepareStatement(query);
                    rs=pst.executeQuery(query);
                    while(rs.next()){
                        if(name.getText().equalsIgnoreCase("") && password.getText().equalsIgnoreCase(""))
                        {JOptionPane.showMessageDialog(null,"Write Username And Password","Write Name & Password",JOptionPane.ERROR_MESSAGE);}
                        else if(name.getText().equalsIgnoreCase(rs.getString("name")) && password.getText().equalsIgnoreCase(rs.getString("password")))
                        {JOptionPane.showMessageDialog(null,"Login Successfully");
                            Tpage tp=new Tpage();
                            tp.show();
                            dispose();}
                        else{
                            JOptionPane.showMessageDialog(null,"Username And Password Is Incorrect","Incorrest",JOptionPane.ERROR_MESSAGE);
                        }
                    }}
                    catch(Exception ex)
                    {ex.printStackTrace();
                        JOptionPane.showMessageDialog(null,ex.getMessage());}
                }
        else if(ge.equalsIgnoreCase("as Student"))
                {
                    try{
                        String query="SELECT name,password FROM student_info WHERE name='"+name.getText()+"' AND password='"+password.getText()+"'";
                        pst=con.prepareStatement(query);
                        rs=pst.executeQuery(query);
                        while(rs.next()){
                            if(name.getText().equalsIgnoreCase("") && password.getText().equalsIgnoreCase(""))
                        {JOptionPane.showMessageDialog(null,"Write Username And Password","Write Name & Password",JOptionPane.ERROR_MESSAGE);}
                            else if(name.getText().equalsIgnoreCase(rs.getString("name")) && password.getText().equalsIgnoreCase(rs.getString("password")))
                            {JOptionPane.showMessageDialog(null,"Login Successfully");
                                Spage stu=new Spage();
                                stu.setVisible(true);
                                dispose();}
                            else{
                                JOptionPane.showMessageDialog(null,"Username And Password Is Incorrect","Incorrest",JOptionPane.ERROR_MESSAGE);
                            }
                        }}
                        catch(Exception ex) 
                        {ex.printStackTrace();
                            JOptionPane.showMessageDialog(null,ex.getMessage());}
                    }//}
        else{
        JOptionPane.showMessageDialog(null,"Select Teacher or Student","Select Anyone",JOptionPane.ERROR_MESSAGE);
        } 
                    //       try{
                        //       String query="Select "
                        //       }
                    //       catch(Exception ex)
                    //       {ex.printStackTrace();
                        //       JOptionPane.showMessageDialog(null,ex.getMessage());}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased

    }//GEN-LAST:event_nameKeyReleased
public String getname()
{return nam;}
    private void taccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taccountMouseClicked
Student std=new Student();
std.setVisible(true);
dispose();
    }//GEN-LAST:event_taccountMouseClicked

    private void saccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saccountMouseClicked
      Account tch=new Account();
      tch.setVisible(true);
      dispose();
    }//GEN-LAST:event_saccountMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      System.exit(1);
    }//GEN-LAST:event_jButton2ActionPerformed
//public String getname()
//{return na;}
//public void setname(String nam)
//{na=nam;}
public static boolean validatename(String name)
{
return name.matches("[A-Z][A-Za-z]*");
}

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel forgot;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel login;
    public static javax.swing.JTextField name;
    public static javax.swing.JPasswordField password;
    private javax.swing.JLabel saccount;
    private javax.swing.JRadioButton student;
    private javax.swing.JLabel taccount;
    private javax.swing.JRadioButton teacher;
    // End of variables declaration//GEN-END:variables
}
