/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Front;

import Database.Connections;
import Student.Spage;

import java.awt.print.PrinterException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import static javax.management.remote.JMXConnectorFactory.connect;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentListener;
import javax.swing.event.UndoableEditListener;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.Element;
import javax.swing.text.Position;
import javax.swing.text.Segment;
import javax.swing.text.Utilities;

/**
 *
 * @author pc
 */
public class View extends javax.swing.JFrame {
private Connection con;
private ResultSet rs;
private Statement st;
private PreparedStatement pst;
Connections connect=new Connections();
int c=0;
    /**
     * Creates new form View
     */
    public View(String title) {
        c++;
        initComponents();
          try{
          String query="SELECT file FROM proposal_submission WHERE assign_title='"+title+"'";
          pst=connect.Conn().prepareStatement(query);
        rs=pst.executeQuery(query);
    File fle=new File("C:\\Program\\"+title+".txt");
    //    File fle=new File(title+".txt");
        FileOutputStream fout=new FileOutputStream(fle);
        if(rs.next())
        {
        InputStream input=rs.getBinaryStream("file");
        byte[] buffer=new byte[1024];
while(input.read(buffer)>0)
        {
            //BufferedReader buff=new BufferedReader(buffer);
//StringBuilder sb=new StringBuilder();
//sb.append(buffer);
            fout.write(buffer);
            FileReader fr=new FileReader(fle);
            BufferedReader br=new BufferedReader(fr);
            area.read(br,null);
        }
        }
        JOptionPane.showMessageDialog(null,"File Readed");
        read();
      }
      catch(Exception ex)
      {ex.printStackTrace();
      JOptionPane.showMessageDialog(null, ex.getMessage());}
//         try{
//        String query="SELECT file_path FROM assignment_submission WHERE sno='"+title+"'";
//         pst=con.prepareStatement(query);
//        rs=pst.executeQuery(query);
//        while(rs.next())
//        {
//        System.out.println(rs.getString("file_path"));
//            FileReader reader=new FileReader(rs.getString("file_path"));
//BufferedReader buff=new BufferedReader(reader);
//area.read(buff,null);
//buff.close();
//        }
//        }
//        catch(Exception ex)
//        {ex.printStackTrace();
//        JOptionPane.showMessageDialog(null,ex.getMessage());}
              }
       
////        int spe=0;
////    int wCount =1+area.getText().length() - area.getText().replaceAll(" ","").length();
////int vows = 0,cons = 0,spa=0,lno=0;
////String sq=area.getText();
////char[] ch=new char[100];
////for(int i = 0; i < sq.length(); i ++)
////{
////ch = sq.toCharArray();
////if(ch[i] == 'a' || ch[i] == 'A' || ch[i] == 'e' || ch[i] == 'E' || ch[i] == 'i' || 
////ch[i] == 'I' || ch[i] == 'o' || ch[i] == 'O' || ch[i] == 'u' || ch[i] == 'U')
////{vows ++;}
////else{
////cons ++;}
//////lno=area.getl
////characters.setText(""+(vows+cons));          
////words.setText(""+wCount);
////lines.setText(""+getlinecount());
////}
////public int getlinecount()
////{
////int totalCharacters = area.getText().length(); 
////int lineCount = (totalCharacters == 0) ? 1 : 0;
////
////try {
////   int offset = totalCharacters; 
////   while (offset > 0) {
////      offset = Utilities.getRowStart(area, offset) - 1;
////      lineCount++;
////   }
////} catch (BadLocationException e) {
////    e.printStackTrace();
////}
////return lineCount;
////}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        words = new javax.swing.JLabel();
        characters = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Project Proposal Submission");

        jLabel2.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        jLabel2.setText("Words:");

        words.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        words.setText("Lines");

        characters.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        characters.setText("Lines");

        jLabel6.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        jLabel6.setText("Characters:");

        jScrollPane2.setViewportView(area);

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(words, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(characters, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(words, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(characters)
                    .addComponent(jLabel6)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void read()
{
int spe=0;
    int wCount =1+area.getText().length() - area.getText().replaceAll(" ","").length();
int vows = 0,cons = 0,spa=0,lno=0;
words.setText(""+wCount);
String sq=area.getText();
char[] ch=new char[100];
for(int i = 0; i < sq.length(); i ++)
{
ch = sq.toCharArray();
if(ch[i] == 'a' || ch[i] == 'A' || ch[i] == 'e' || ch[i] == 'E' || ch[i] == 'i' || 
ch[i] == 'I' || ch[i] == 'o' || ch[i] == 'O' || ch[i] == 'u' || ch[i] == 'U')
{vows ++;}
else if(Character.isWhitespace(ch[i])){
spa++;
}
else{
cons ++;}
characters.setText(""+(vows+cons));          
}
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try{
boolean complete=area.print();
if(complete){
JOptionPane.showMessageDialog(null,"Done Printing","Information",JOptionPane.INFORMATION_MESSAGE);
}else{
JOptionPane.showMessageDialog(null,"Printing","Printer",JOptionPane.ERROR_MESSAGE);
}
}
catch(PrinterException e){
JOptionPane.showMessageDialog(null, e.getMessage());
}
    }//GEN-LAST:event_jButton2ActionPerformed
//public void readfile(String title)
//{
//  
//}
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//               new View("adil").setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane area;
    private javax.swing.JLabel characters;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel words;
    // End of variables declaration//GEN-END:variables
}
