/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Teacher;

import Database.Connections;
import Front.Front;
import Front.Splash;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author pc
 */
public class tforget_account extends javax.swing.JFrame {
Connection con;
Statement st;
PreparedStatement pst;
ResultSet rs;
Connections conns=new Connections();
Timer timer;int count=0;
    /**
     * Creates new form tforget_account
     */
    public tforget_account() {
        initComponents();
        pro.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pro = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(name);
        name.setBounds(290, 70, 230, 30);
        getContentPane().add(email);
        email.setBounds(290, 110, 230, 30);

        password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(password);
        password.setBounds(110, 350, 470, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 70, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Email");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 110, 160, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 210, 150, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 210, 160, 30);

        pro.setBackground(new java.awt.Color(0, 153, 0));
        pro.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pro);
        pro.setBounds(100, 310, 490, 20);

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.green, java.awt.Color.green));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(90, 50, 490, 130);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 4, true));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(130, 190, 430, 100);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Back");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      int flag=0;
        pro.setVisible(true);
        startprogress();
        try{
        String query="SELECT name,email,password FROM teacher_info WHERE name='"+name.getText()+"' AND email='"+email.getText()+"'";
       st=conns.Conn().createStatement();
        rs=st.executeQuery(query);
        while(rs.next()){
        if(name.getText().equalsIgnoreCase(rs.getString("name")) && email.getText().equalsIgnoreCase(rs.getString("email")))
        {password.setText("Your Account Password Is :"+rs.getString("password"));}
        else
        {flag=1;}
        }}
        catch(Exception ex)
        {ex.printStackTrace();
        JOptionPane.showMessageDialog(null,ex.getMessage());}
if(flag==1)
{password.setText("Your Above Information Is Not Correct");}
//     startprogress();
    }//GEN-LAST:event_jButton2ActionPerformed
//// public void getpass()
//// {
//// try{
////     String query="SELECT password FROM teacher_info WHERE name='"+name.getText()+"' && email='"+email.getText()+"'";
////     st=conns.Conn().createStatement();
////        rs=st.executeQuery(query);
////        while(rs.next())
////        {
////        password.setText("Your Password Is "+rs.getString("passsowrd"));
////        }
//// }
//// catch(Exception ex)
//// {ex.printStackTrace();
//// JOptionPane.showMessageDialog(null,ex.getMessage());
//// }

    private void startprogress()
  {
     
Front fr=new Front();
      timer =new Timer(50,new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e) {
pro.setValue(count);
if(count==pro.getMaximum())
{
timer.stop();
pro.setVisible(false);
}
   count++;     }
    });
 timer.start();
  }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       name.setText("");
        email.setText("");
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Front fr=new Front();
        fr.setVisible(true);
        dispose();
                
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       System.exit(1);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name;
    private javax.swing.JLabel password;
    private javax.swing.JProgressBar pro;
    // End of variables declaration//GEN-END:variables
}
